server:
  port: 8082


spring:
  application:
    name: upload-service
  servlet:
    multipart: 5MB         #最大限制5M

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5   #每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10   #10秒不发送就停止
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

